# Дообучение RuBERT для классификации сообщений

Эксперимент с fine-tuning трансформерной языковой модели для многоклассовой классификации сообщений; используются macro precision, recall, F1 и accuracy.

In [1]:
import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
seed = 42
np.random.seed(seed)

In [4]:
import re


def extract_text(msg):
    if not isinstance(msg, list):
        return msg

    result_text = ''
    for item in msg:
        if isinstance(item, str):
            result_text += (item + " ")
        else:
            result_text += (item['text'] + " ")
    return result_text

def prepoccess_dataset(df):
    preproccessed_df = df.copy()
    preproccessed_df = df.dropna(subset=['text'])
    preproccessed_df.reset_index(drop=True, inplace=True)
    preproccessed_df['text'] = preproccessed_df['text'].map(lambda x: extract_text(x))
    preproccessed_df['text_clean_nums'] = preproccessed_df['text'].map(lambda x: re.sub(r'\d', '', x))
    preproccessed_df = preproccessed_df[preproccessed_df['text_clean_nums'] != '']
    return preproccessed_df

def chat_to_df(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data_json = json.load(f)

    user_id = []
    usernames = []
    dates = []
    texts = []
    for msg in data_json['messages']:
        if msg['type'] == 'message':
            user_id.append(msg['from_id'])
            if 'forwarded_from' in msg.keys():
                usernames.append(msg['forwarded_from'])
            else:
                usernames.append(msg['from'])
            dates.append(msg['date'])
            texts.append(msg['text'])

    df = pd.DataFrame({
        'user_id': user_id,
        'username': usernames,
        'date': dates,
        'text': texts,
    })
    
    return prepoccess_dataset(df)

In [5]:
json_path = r'../../data/chats/marakasi_14.02.2026.json'
df = chat_to_df(json_path)

In [6]:
df.head()

,user_id,username,date,text,text_clean_nums
0,user674227701,свитистер МТС,2024-08-21T22:53:00,А мне,А мне
1,user790422015,Ири,2024-08-21T22:53:02,💋💋💋,💋💋💋
2,user790422015,Ири,2024-08-21T22:53:15,Пожалуйста не надо альфа Лера,Пожалуйста не надо альфа Лера
3,user872595910,ВАЛЬРА!,2024-08-21T22:53:20,Да,Да
4,user790422015,Ири,2024-08-21T22:53:23,А что ты хочешь,А что ты хочешь

In [7]:
df = df.drop(columns=['user_id', 'date'])

In [8]:
marakasi_users = [
    'свитистер МТС', 'Ири', 'ВАЛЬРА!', 'Шорт', 'Арина Колошек🌏',
    'Соня🤘', 'Егорчек🙄', 'Denis ss', 'dandelions', 'Умка', 'nuta',
    '見知らぬ人 アイ', 'Кибержаба'
]

marakasi_users = [
    'свитистер МТС', 'Ири', 'ВАЛЬРА!', 'Шорт', 'Арина Колошек🌏',
    'Соня🤘', 'Егорчек🙄', 'Denis ss', 'dandelions', 'Умка', 'nuta',
]

In [9]:
df = df[df['username'].isin(marakasi_users)]

In [10]:
df['username'].value_counts()

username
dandelions        16662
свитистер МТС     10964
ВАЛЬРА!           10634
Соня🤘              4487
Шорт               4269
Егорчек🙄           3695
Ири                2461
Denis ss           2387
Арина Колошек🌏     2268
Умка               2161
nuta               2023
Name: count, dtype: int64

In [11]:
#df, _ = train_test_split(df, stratify=df['username'], train_size=0.2)

# rus = RandomUnderSampler(random_state=42)
# X_df = df.drop(columns=['username'])
# y_df = df[['username']]
# X_resample, y_resample = rus.fit_resample(X_df, y_df)
# df = pd.concat([X_resample, y_resample], axis=1)

In [12]:
df['username'].value_counts()

username
dandelions        16662
свитистер МТС     10964
ВАЛЬРА!           10634
Соня🤘              4487
Шорт               4269
Егорчек🙄           3695
Ири                2461
Denis ss           2387
Арина Колошек🌏     2268
Умка               2161
nuta               2023
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
df['label'] = le.fit_transform(df['username'])

In [15]:
id2label = {int(i): str(label) for i, label in enumerate(le.classes_)}
label2id = {str(label): int(i) for i, label in enumerate(le.classes_)}

In [16]:
id2label

{0: 'Denis ss',
 1: 'dandelions',
 2: 'nuta',
 3: 'Арина Колошек🌏',
 4: 'ВАЛЬРА!',
 5: 'Егорчек🙄',
 6: 'Ири',
 7: 'Соня🤘',
 8: 'Умка',
 9: 'Шорт',
 10: 'свитистер МТС'}

In [17]:
df = df.drop(columns=['text'])

In [18]:
df.head()

        username                text_clean_nums  label
0  свитистер МТС                          А мне     10
1            Ири                            💋💋💋      6
2            Ири  Пожалуйста не надо альфа Лера      6
3        ВАЛЬРА!                             Да      4
4            Ири                А что ты хочешь      6

In [19]:
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer

W0329 19:01:51.590000 25392 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

WARNING:tensorflow:From C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [20]:
model_id = 'DeepPavlov/rubert-base-cased-conversational'
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [21]:
dataset = Dataset.from_pandas(df[['text_clean_nums', 'label']])
dataset = dataset.class_encode_column("label")
dataset = dataset.train_test_split(test_size=0.2, stratify_by_column="label", seed=42)

Stringifying the column:   0%|          | 0/62011 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/62011 [00:00<?, ? examples/s]

In [22]:
def tokenize_func(example):
    return tokenizer(example['text_clean_nums'], padding='max_length', max_length=128, truncation=True)

tokenized_dataset = dataset.map(tokenize_func, batched=True)

Map:   0%|          | 0/49608 [00:00<?, ? examples/s]

Map:   0%|          | 0/12403 [00:00<?, ? examples/s]

In [23]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    num_labels=len(df['label'].unique()),
    id2label=id2label, label2id=label2id,
    device_map='auto', dtype='auto'
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at DeepPavlov/rubert-base-cased-conversational and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [24]:
for param in model.base_model.parameters():
    param.requires_grad = False

for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Обучаемый слой: {name}")

Обучаемый слой: classifier.weight
Обучаемый слой: classifier.bias

In [25]:
from sklearn.utils.class_weight import compute_class_weight

weights = compute_class_weight(
    class_weight='balanced', 
    classes=np.unique(dataset['train']['label']), 
    y=dataset['train']['label']
)

In [26]:
np.unique(dataset['train']['label'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
weights

array([2.36116135, 0.33834633, 0.51417378, 2.78727947, 2.48611807,
       0.53013027, 1.52564891, 2.29041045, 1.25621676, 2.60833903,
       1.32059098])

In [28]:
id2label

{0: 'Denis ss',
 1: 'dandelions',
 2: 'nuta',
 3: 'Арина Колошек🌏',
 4: 'ВАЛЬРА!',
 5: 'Егорчек🙄',
 6: 'Ири',
 7: 'Соня🤘',
 8: 'Умка',
 9: 'Шорт',
 10: 'свитистер МТС'}

In [29]:
from torch import nn
import torch

In [30]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'

In [31]:
device

'cuda'

In [32]:
import numpy as np
import evaluate

def compute_metrics(eval_pred):
    precision_metric = evaluate.load("precision")
    recall_metric = evaluate.load("recall")
    f1_metric = evaluate.load("f1")
    accuracy_metric = evaluate.load("accuracy")
    
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    
    results = {}
    results.update(precision_metric.compute(predictions=predictions, references=labels, average='macro'))
    results.update(recall_metric.compute(predictions=predictions, references=labels, average='macro'))
    results.update(f1_metric.compute(predictions=predictions, references=labels, average='macro'))
    results.update(accuracy_metric.compute(predictions=predictions, references=labels))
    
    return results

In [33]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        
        loss_fct = nn.CrossEntropyLoss(weight=torch.tensor(weights).float().to(device))
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        
        return (loss, outputs) if return_outputs else loss

In [35]:
training_args = TrainingArguments(
    output_dir="../../models/marakasi_rubert",
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    fp16=True,
    num_train_epochs=15,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="no",
    load_best_model_at_end=False,
    logging_strategy='epoch'
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics
)

trainer.train()

The model is already on multiple devices. Skipping the move to device specified in `args`.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from C:\Users\Denis\_netrc.
wandb: Currently logged in as: salnikovdenis44 (salnikovdenis44-omstu) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f30f' in position 554: character maps to <undefined>
Call stack:
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\kernelbase.py", line 400, in dispatch_shell
    await result
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\ipykernel\zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Denis\AppData\Local\Temp\ipykernel_25392\3646334738.py", line 24, in <module>
    trainer.train()
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\trainer.py", line 2325, in train
    return inner_training_loop(
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\trainer.py", line 2573, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\trainer_callback.py", line 506, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\trainer_callback.py", line 556, in call_event
    result = getattr(callback, event)(
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\integrations\integration_utils.py", line 966, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\transformers\integrations\integration_utils.py", line 898, in setup
    self._wandb.config.update(combined_dict or {}, allow_val_change=True)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_config.py", line 189, in update
    self._callback(data=sanitized)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_run.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_run.py", line 458, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Denis\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_run.py", line 1404, in _config_callback
    logger.info(f"config_cb {key} {val} {data}")
Message: "config_cb None None {'return_dict': True, 'output_hidden_states': False, 'torchscript': False, 'dtype': None, 'pruned_heads': {}, 'tie_word_embeddings': True, 'chunk_size_feed_forward': 0, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'architectures': ['BertModel'], 'finetuning_task': None, 'id2label': {0: 'Denis ss', 1: 'dandelions', 2: 'nuta', 3: 'Арина Колошек🌏', 4: 'ВАЛЬРА!', 5: 'Егорчек🙄', 6: 'Ири', 7: 'Соня🤘', 8: 'Умка', 9: 'Шорт', 10: 'свитистер МТС'}, 'label2id': {'Denis ss': 0, 'dandelions': 1, 'nuta': 2, 'Арина Колошек🌏': 3, 'ВАЛЬРА!': 4, 'Егорчек🙄': 5, 'Ири': 6, 'Соня🤘': 7, 'Умка': 8, 'Шорт': 9, 'свитистер МТС': 10}, 'task_specific_params': None, 'problem_type': None, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': None, 'pad_token_id': 0, 'eos_token_id': None, 'sep_token_id': None, 'decoder_start_token_id': None, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'num_beam_groups': 1, 'diversity_penalty': 0.0, '_name_or_path': 'DeepPavlov/rubert-base-cased-conversational', 'transformers_version': '4.57.6', 'directionality': 'bidi', 'model_type': 'bert', 'output_past': True, 'pooler_fc_size': 768, 'pooler_num_attention_heads': 12, 'pooler_num_fc_layers': 3, 'pooler_size_per_head': 128, 'pooler_type': 'first_token_transform', 'tf_legacy_loss': False, 'use_bfloat16': False, 'vocab_size': 119547, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'hidden_act': 'gelu', 'intermediate_size': 3072, 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02, 'layer_norm_eps': 1e-12, 'position_embedding_type': 'absolute', 'use_cache': True, 'classifier_dropout': None, 'output_attentions': False, 'output_dir': '../../models/marakasi_rubert', 'overwrite_output_dir': False, 'do_train': False, 'do_eval': True, 'do_predict': False, 'eval_strategy': 'epoch', 'prediction_loss_only': False, 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 32, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'eval_accumulation_steps': None, 'eval_delay': 0, 'torch_empty_cache_steps': None, 'learning_rate': 5e-05, 'weight_decay': 0.01, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 15, 'max_steps': -1, 'lr_scheduler_type': 'cosine', 'lr_scheduler_kwargs': None, 'warmup_ratio': 0.0, 'warmup_steps': 0, 'log_level': 'passive', 'log_level_replica': 'warning', 'log_on_each_node': True, 'logging_dir': '../../models/marakasi_rubert\\\\runs\\\\Mar29_19-03-12_DESKTOP-V0CC14Q', 'logging_strategy': 'epoch', 'logging_first_step': False, 'logging_steps': 500, 'logging_nan_inf_filter': True, 'save_strategy': 'no', 'save_steps': 500, 'save_total_limit': None, 'save_safetensors': True, 'save_on_each_node': False, 'save_only_model': False, 'restore_callback_states_from_checkpoint': False, 'no_cuda': False, 'use_cpu': False, 'use_mps_device': False, 'seed': 42, 'data_seed': None, 'jit_mode_eval': False, 'bf16': False, 'fp16': True, 'fp16_opt_level': 'O1', 'half_precision_backend': 'auto', 'bf16_full_eval': False, 'fp16_full_eval': False, 'tf32': None, 'local_rank': 0, 'ddp_backend': None, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'debug': [], 'dataloader_drop_last': False, 'eval_steps': None, 'dataloader_num_workers': 0, 'dataloader_prefetch_factor': None, 'past_index': -1, 'run_name': None, 'disable_tqdm': False, 'remove_unused_columns': True, 'label_names': None, 'load_best_model_at_end': False, 'metric_for_best_model': None, 'greater_is_better': None, 'ignore_data_skip': False, 'fsdp': [], 'fsdp_min_num_params': 0, 'fsdp_config': {'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}, 'fsdp_transformer_layer_cls_to_wrap': None, 'accelerator_config': {'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None}, 'parallelism_config': None, 'deepspeed': None, 'label_smoothing_factor': 0.0, 'optim': 'adamw_torch_fused', 'optim_args': None, 'adafactor': False, 'group_by_length': False, 'length_column_name': 'length', 'report_to': ['tensorboard', 'wandb'], 'project': 'huggingface', 'trackio_space_id': 'trackio', 'ddp_find_unused_parameters': None, 'ddp_bucket_cap_mb': None, 'ddp_broadcast_buffers': None, 'dataloader_pin_memory': True, 'dataloader_persistent_workers': False, 'skip_memory_metrics': True, 'use_legacy_prediction_loop': False, 'push_to_hub': False, 'resume_from_checkpoint': None, 'hub_model_id': None, 'hub_strategy': 'every_save', 'hub_token': '<HUB_TOKEN>', 'hub_private_repo': None, 'hub_always_push': False, 'hub_revision': None, 'gradient_checkpointing': False, 'gradient_checkpointing_kwargs': None, 'include_inputs_for_metrics': False, 'include_for_metrics': [], 'eval_do_concat_batches': True, 'fp16_backend': 'auto', 'push_to_hub_model_id': None, 'push_to_hub_organization': None, 'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>', 'mp_parameters': '', 'auto_find_batch_size': False, 'full_determinism': False, 'torchdynamo': None, 'ray_scope': 'last', 'ddp_timeout': 1800, 'torch_compile': False, 'torch_compile_backend': None, 'torch_compile_mode': None, 'include_tokens_per_second': False, 'include_num_input_tokens_seen': 'no', 'neftune_noise_alpha': None, 'optim_target_modules': None, 'batch_eval_metrics': False, 'eval_on_start': False, 'use_liger_kernel': False, 'liger_kernel_config': None, 'eval_use_gather_object': False, 'average_tokens_across_devices': True}"
Arguments: ()

TrainOutput(global_step=23265, training_loss=2.2642483994701, metrics={'train_runtime': 2292.7678, 'train_samples_per_second': 324.551, 'train_steps_per_second': 10.147, 'total_flos': 4.895050487049216e+16, 'train_loss': 2.2642483994701, 'epoch': 15.0})

In [52]:
trainer.save_model("../../models/marakasi_final_model")

In [40]:
from transformers import pipeline

In [75]:
path = r"../../models/marakasi_final_model"

model = AutoModelForSequenceClassification.from_pretrained(
    path,
    device_map='auto', dtype='auto'
)

In [76]:
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer, device_map='auto')

Device set to use cuda:0

In [80]:
classifier("моя мечта сука")

[{'label': 'dandelions', 'score': 0.2715003192424774}]